server.port: 8080

#addressClient:
#  baseUrl: http://localhost:8081
#
#customerClient:
#  baseUrl: http://localhost:8081

addressClient:
  baseUrl: http://${CUSTOMER_SVC:localhost}:8081

customerClient:
  baseUrl: http://${CUSTOMER_SVC:localhost}:8081

spring:
  application:
    name: front-service